import { Header } from "@app/components/header/header";

import type { Metadata } from "next";

import { poppins } from "@app/fonts/poppins";
import "@app/styles/reset.scss";
import "@app/styles/global.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
